In [3]:
#storing data

list = ['sinner', 'djokovic', 'sabalenka']

tuple = ('sinner', 'djokovic', 'sabalenka')

dictionary = {'favourite_mens': 'sinner', 'favourite_womens': 'sabalenka'}

print(f"favourites are: {dictionary['favourite_mens']} and {dictionary['favourite_womens']}")

favourites are: sinner and sabalenka


In [4]:
dictionary = {'favourite_mens': 'sinner', 'favourite_womens': 'sabalenka'}

with open('favourites.txt', 'r') as f:
    for line in f:
        print(line)


favourites are: sinner and sabalenka


In [7]:
import csv

matches = [
    {'winner': 'Sinner', 'loser': 'Kecmanovic', 'score': '6-3 6-4 6-2'},
    {'winner': 'Djokovic', 'loser': 'Cilic', 'score': '6-1 6-3 6-2'},
]

with open('matches.csv', 'w', newline='') as f:
    fieldnames = ['winner', 'loser', 'score']
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(matches)


In [8]:
import json

data = {
    "round": "R1",
    "matches": [
        {"winner": "Sinner", "loser": "Kecmanovic", "score": "6-3 6-4 6-2"},
        {"winner": "Djokovic", "loser": "Cilic", "score": "6-1 6-3 6-2"}
    ]
}

with open('results.json', 'w') as f:
    json.dump(data, f, indent=2)

with open('results.json', 'r') as f:
    loaded = json.load(f)
    print(loaded['matches'][0])

{'winner': 'Sinner', 'loser': 'Kecmanovic', 'score': '6-3 6-4 6-2'}


In [ ]:
wimbledon_r1_results = [
    {
        "winner": "Jannik Sinner",
        "loser": "Miomir Kecmanovic",
        "score": "4-6, 6-3, 6-7(6), 6-2, 6-3",
        "court": "Centre Court"
    },
    {
        "winner": "Novak Djokovic",
        "loser": "Yibing Wu",
        "score": "6-4, 5-7, 6-4, 6-4",
        "court": "Centre Court"
    },
    {
        "winner": "Daniil Medvedev",
        "loser": "Marin Cilic",
        "score": "6-1, 6-2, 6-4",
        "court": "Court 1"
    },
    {
        "winner": "Felix Auger-Aliassime",
        "loser": "Aleksandr Shevchenko",
        "score": "6-3, 6-1, 6-4",
        "court": "Court 2"
    },
    {
        "winner": "Hubert Hurkacz",
        "loser": "Casper Ruud",
        "score": "6-4, 6-2, 7-6(7)",
        "court": "Court 3"
    },
    {
        "winner": "Aryna Sabalenka",
        "loser": "Teodora Kostovic",
        "score": "6-2, 6-3",
        "court": "Centre Court"
    },
    {
        "winner": "Jessica Pegula",
        "loser": "Darja Vidmanova",
        "score": "7-5, 6-3",
        "court": "Court 1"
    },
    {
        "winner": "Roman Safiullin",
        "loser": "Andrey Rublev",
        "score": "6-4, 6-7(6), 3-6, 6-3, 7-6(12)",
        "court": "Court 2"
    },
]

with open('Day1_Results.json', 'w') as f:
    json.dump(wimbledon_r1_results, f, indent=2)



In [ ]:
def load_results(round):
    try:
        with open('Day1_Results.json', 'r') as f:
            return json.load(f)
    except FileNotFoundError as e:
        print(e)

def court_results(round, court):
    with open('Day1_Results.json', 'r') as f:
        results = json.load(f)
        filtered_results = []
        for x in results:
            if x['court'] == court:
                filtered_results.append(x)
    return filtered_results


with open('Day1_Results.csv', 'w') as f:
    fieldnames = ['winner', 'loser', 'score', 'court']
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writerows(court_results(1, 'Centre Court'))


In [24]:
import numpy as np

a = np.zeros((5,5))
a[0, :] = 1
a[4, :] = 1
a[:, 0] = 1
a[1, 4] = 1
a[2, 2] = 9
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]


In [16]:
import pandas as pd


matches = pd.read_csv('../data/atp_matches_till_2022.csv')

'''
players = pd.read_csv('../data/atp_players_till_2022.csv')
print(df.shape)
print(df.columns.tolist())

rankings = pd.read_csv('../data/atp_rankings_till_2022.csv')
print(df.shape)
print(df.columns.tolist())

grass_matches = matches.loc[matches['surface'] == 'Grass']
sinner_wins = grass_matches.loc[grass_matches['winner_name'] == 'Jannik Sinner']
sinner_wins_count = len(sinner_wins)
print(sinner_wins_count)

'''

print(matches[matches['winner_name'].str.contains('Federer')]['winner_name'].unique())
print(matches[matches['winner_name'].str.contains('Nadal')]['winner_name'].unique())




<StringArray>
['Roger Federer']
Length: 1, dtype: str
<StringArray>
['Rafael Nadal']
Length: 1, dtype: str


In [19]:
import pandas as pd


matches = pd.read_csv('../data/atp_matches_till_2022.csv')


h2h_underdog_wins = matches[(matches['loser_name'] == 'Roger Federer') & (matches['winner_name'] == 'Rafael Nadal')]

print(len(h2h_underdog_wins))

24


In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
import os


matches = pd.read_csv('../data/atp_matches_till_2022.csv')

winCount = len(matches[matches['winner_name'] == 'Rafael Nadal'])
lossCount = len(matches[matches['loser_name'] == 'Rafael Nadal'])



